spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.8.100:4002/gaofenshuo_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password: 123456
    sharding:
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds0
      tables:
        uc_sys_evaluationlog:
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: ds0
          table-strategy:
            standard:
              sharding-column: created_at
              precise-algorithm-class-name: com.gfs.shardingjdbcdemo.config.CreateDatePreciseShardingAlgorithm
              range-algorithm-class-name: com.gfs.shardingjdbcdemo.config.CreateDateRangeShardingAlgorithm
            complex:
              shardingColumns:
              algorithmClassName:
#            inline:
#              sharding-column: id
#              algorithm-expression: uc_sys_evaluationlog$->{id % 2}
#          actual-data-nodes: ds0.uc_sys_evaluationlog_$->{2019..2020}$->{['00','01','02','03','04','05','06','07','08','09','10','11','12']},
          actual-data-nodes: ds0.uc_sys_evaluationlog_$->{2019}$->{['01','02']},
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true

